package object

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/types"
	"strings"

	"golang.org/x/tools/go/packages"
)

// FoundObject encapsulates every angle of the object we want to manipulate.
type FoundObject struct {
	Object types.Object      // Type system details (useful for finding callers)
	File   *ast.File         // The specific file AST where it resides
	Node   ast.Node          // The individual AST declaration node (to cut/paste)
	Pkg    *packages.Package // The package containing this object
}

// Code converts any in-memory AST node type into its formatted Go string representation.
func (o FoundObject) Code() (string, error) {
	if o.Node == nil {
		return "", fmt.Errorf("no AST node found to print")
	}
	if o.Pkg.Fset == nil {
		return "", fmt.Errorf("token.FileSet is required to format code structures")
	}

	var buf bytes.Buffer

	switch node := o.Node.(type) {
	case *ast.Field:
		// 1. Isolate and print its Type expression
		if err := format.Node(&buf, o.Pkg.Fset, node.Type); err != nil {
			return "", fmt.Errorf("failed to format field type: %w", err)
		}

		typeStr := buf.String()
		typeStr = strings.TrimPrefix(typeStr, "func")

		// 2. Extract and combine names (handles grouped definitions like `a, b int`)
		var names []string
		for _, ident := range node.Names {
			if ident != nil {
				names = append(names, ident.Name)
			}
		}

		// 3. Assemble the raw method signature text
		var rawResult string
		if len(names) > 0 {
			separator := " "
			if strings.HasPrefix(typeStr, "(") {
				separator = "" // Avoids space like "CreateVM (ctx..."
			}
			rawResult = strings.Join(names, ", ") + separator + typeStr
		} else {
			rawResult = typeStr
		}

		// 4. SANITIZER: Collapse erratic newlines and layout tabs caused by position conflicts
		return collapseWhitespace(rawResult), nil

	case *ast.FuncDecl:
		// For standalone functions/methods, we print them natively
		if err := format.Node(&buf, o.Pkg.Fset, node); err != nil {
			return "", fmt.Errorf("failed to format node: %w", err)
		}

		// If it's just a declaration without a body (or we want a clean single-line snippet),
		// we can sanitize it if it spans multiple lines awkwardly.
		if node.Body == nil {
			return collapseWhitespace(buf.String()), nil
		}
		return buf.String(), nil

	default:
		if err := format.Node(&buf, o.Pkg.Fset, node); err != nil {
			return "", fmt.Errorf("failed to format node of type %T: %w", node, err)
		}
		return buf.String(), nil
	}
}

// collapseWhitespace strips out newlines, carriage returns, and groups of tabs/spaces,
// joining the remaining words with a single clean space character.
func collapseWhitespace(input string) string {
	words := strings.Fields(input)
	result := strings.Join(words, " ")

	// 1. Fix trailing commas before closing parentheses generated by multi-line layouts
	result = strings.ReplaceAll(result, ", )", ")")

	// 2. Quick cosmetic fix: ensure standard Go spacing around commas in parameters
	result = strings.ReplaceAll(result, ", ", ",")
	result = strings.ReplaceAll(result, ",", ", ")

	return result
}
